<a href="https://colab.research.google.com/github/matthewchennn/PyTorch-Learning/blob/main/basic_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
a = torch.tensor([2,4,5])
b = torch.tensor([2,4,10])
t = torch.add(a,b)
print(t)

tensor([ 4,  8, 15])


In [ ]:
# dot product
mult = torch.multiply(a,b)
print(mult)
# division
div = torch.divide(a,b)
print(div)

tensor([ 4, 16, 50])
tensor([1.0000, 1.0000, 0.5000])


In [ ]:
rem = torch.remainder(a,b)
print(rem)

tensor([0, 0, 5])


In [ ]:
# exponential
exp = torch.pow(a,b)
print(exp)

tensor([      4,     256, 9765625])


In [ ]:
# Re-assigning value of a
a + b
print(a)
a.add_(b)
print(a)

tensor([ 4,  8, 15])
tensor([ 6, 12, 25])
