<a href="https://colab.research.google.com/github/matthewchennn/PyTorch-Learning/blob/main/Tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
my_torch = torch.arange(15)
print(my_torch)



tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


In [ ]:
# Reshapce

my_torch = my_torch.reshape(3,5)
print(my_torch)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


In [ ]:
# -1 will autofit
my_torch2 = my_torch.reshape(-1,5)
print(my_torch2)
my_torch2 = my_torch.reshape(5,-1)
print(my_torch2)


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])


In [ ]:
my_torch3 = torch.arange(10)

my_torch4 = my_torch3.view(2,5) # torch.view only creates a "view" of the tensor, the original data is unimpacted
print(my_torch4)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [ ]:
my_torch5 = torch.arange(10)
print(my_torch5)

my_torch6 = my_torch5.reshape(2,5)
print(my_torch6)



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [ ]:
my_torch5[1] = 1110
print(my_torch5)
print(my_torch6) # notice both terms are updated. WHEN A CHANGE IS MADE WITH RESHAPE
                 # OR VIEW, IT AUTOMATICALLY GETS UPDATED


tensor([   0, 1110,    2,    3,    4,    5,    6,    7,    8,    9])
tensor([[   0, 1110,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [ ]:
# Slices
my_torch7 = torch.arange(12)
print(my_torch7)

# takes the 7th item in the tensor
my_torch7[7]


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


tensor(7)

In [ ]:
# grab a slice of the seocond column
torch8 = my_torch7.reshape(6,2)
my_torch8 = torch8[:,1]
print(my_torch8)

tensor([ 1,  3,  5,  7,  9, 11])
